fix undefined reference to `service_arguments_free' in libisulad_img.so
Signed-off-by: WangFengTu <wangfengtu@huawei.com>
(cherry picked from commit 6cfb99d449ba01138c3af8bfd054c1ba98e31395)